# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b442d98050f23e349cf27f9d511227c79a9f6100ff1d4a089318c6fcef81aae39de34a8eace9930b0edf7f72964dc432f7bf47cf308cb4ed9dc1670474e128fe

test:
  secret_key_base: 952d7bb8a5e33d841e00bd34e0c6ecc91117035405aada0a075936bb322ee04a656cb6c52bc1c31ac3068814022e86b43ef411da7bf288bd18f4d3b52f43f849

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
